<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-25T17:25:54Z" name="Suite" finished-at="2021-03-25T17:26:10Z" duration-ms="16287">
    <groups>
    </groups>
    <test started-at="2021-03-25T17:25:54Z" name="Test" finished-at="2021-03-25T17:26:10Z" duration-ms="16287">
      <class name="com.learnautomation.testcases.LoginTestPoster">
        <test-method is-config="true" signature="suiteSetUp()[pri:0, instance:com.learnautomation.testcases.LoginTestPoster@928763c]" started-at="2021-03-25T22:55:53Z" name="suiteSetUp" finished-at="2021-03-25T22:55:54Z" duration-ms="512" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteSetUp -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.learnautomation.testcases.LoginTestPoster@928763c]" started-at="2021-03-25T22:55:54Z" name="setup" finished-at="2021-03-25T22:56:02Z" duration-ms="8410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginApp()[pri:0, instance:com.learnautomation.testcases.LoginTestPoster@928763c]" started-at="2021-03-25T22:56:02Z" name="loginApp" finished-at="2021-03-25T22:56:06Z" duration-ms="3537" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MY ACCOUNT] but found [MY ACCOUN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [MY ACCOUN]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.learnautomation.testcases.LoginTestPoster.loginApp(LoginTestPoster.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginApp -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.learnautomation.testcases.LoginTestPoster@928763c]" started-at="2021-03-25T22:56:06Z" name="tearDownMethod" finished-at="2021-03-25T22:56:09Z" duration-ms="3441" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginApp status=FAILURE method=LoginTestPoster.loginApp()[pri:0, instance:com.learnautomation.testcases.LoginTestPoster@928763c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.learnautomation.testcases.LoginTestPoster@928763c]" started-at="2021-03-25T22:56:09Z" name="tearDown" finished-at="2021-03-25T22:56:10Z" duration-ms="879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.learnautomation.testcases.LoginTestPoster -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
